FROM maven: 3.8.4-jdk-8 AS build    #Pega a versão do maven para a criação do nosso container com nossa aplicação 

COPY src /app/src   // Uma cópia dos arquivos do nosso projeto
COPY pom xml /app   // Copia do nosso pom
Docker _
        |
        |___ App
                |
                |__ Src

